name: CI/CD Pipeline for Node.js App

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install
      
      - name: Run Tests
        run: npm test

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Build Docker Image
        run: |
          docker build -t your-dockerhub-username/nodejs-app:${{ github.sha }} .
      
      - name: Push Docker Image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push your-dockerhub-username/nodejs-app:${{ github.sha }}
      
      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

  notify:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Notify Success
        if: success()
        run: echo "Deployment succeeded!"
      
      - name: Notify Failure
        if: failure()
        run: echo "Deployment failed!"

